In [2]:
import numpy as np

In [3]:
#numpy array'ler homojendir yani dizi içindeki tüm elemanlar aynı veri tipinde olmalı  
numpy_array = np.array([0,1,2,3,4,5,6,7,8,9,10,])
print("Numpy dizisi :")
print(numpy_array)

Numpy dizisi :
[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
# .ndim ifadesi numpy array'in boyutunu döndürür
numpy_array1=np.array([11,12,13,14,15])
numpy_array2=np.array([[11,12,13,14,15]])
numpy_array3=np.array([[20,21,22,23,],[24,25,26,27]])
print(numpy_array1.ndim)
print(numpy_array2.ndim)
print(numpy_array3.ndim)
print(numpy_array1)
print(numpy_array2)
print(numpy_array3)

1
2
2
[11 12 13 14 15]
[[11 12 13 14 15]]
[[20 21 22 23]
 [24 25 26 27]]


In [5]:
# .ndim ifadesi numpy array'in boyutunu döndürür
numpy_array1=np.array([11,12,13,14,15])
numpy_array2=np.array([[11,12,13,14,15]])
numpy_array3=np.array([[20,21,22,23,],[24,25,26,27]])
print(numpy_array1.ndim)
print(numpy_array2.ndim)
print(numpy_array3.ndim)
print(numpy_array1)
print(numpy_array2)
print(numpy_array3)

1
2
2
[11 12 13 14 15]
[[11 12 13 14 15]]
[[20 21 22 23]
 [24 25 26 27]]


In [6]:
#.shape numpy arrayinin kaç satır ve sutündan oluştuğunu gösteren bir tupple dönen bir fonksiyon
#numpy_array1 için (5,) -> ???  numpy_array2 için (1, 5) -> 1 satır 5 sutün numpy_array3 için (2, 4) -> 2 satır 4 sutün
print(numpy_array1.shape)#.shape ifadesi, her boyuttaki eleman sayısını gösterir. numpy_array1 için tek boyutlu olduğu için ikinci bir sayı yoktur ve (5,) olarak döner
print(numpy_array2.shape)#normalde numpy_array2 için (1, 5) dönerken shape[0] dediğimde 1 shape[1] dediğimde 5 dönüyor
print(numpy_array2.shape[0])#bu şekilde yazdığımızda shape fonksiyonundan dönen tupple'ın hangi indisini yazacağımızı söylemiş oluyoruz sanırım
print(numpy_array2.shape[1])
print(numpy_array2[0].shape)
print(numpy_array3.shape)
print(numpy_array3.shape[1])
print(numpy_array3[0].shape)#tek boyutlu dizi gibi döndürmüş oldum

(5,)
(1, 5)
1
5
(5,)
(2, 4)
4
(4,)


In [7]:
#burada anlamadığım kısımlar var malesef ????? matris için eleman sayısı mı döndürecek yoksa satır sayısını mı 
#len fonksiyonu nesnelerin uzunluğunu döndürür.numpy_array tek boyutlu bir dizi olduğu için ilk boyutundaki eleman sayısını döndürür
#numpy_array2 ve numpy_array3 iki boyutlu dizeler olduğu için bu dizilerinin ilk boyutundaki eleman sayısını döndürür bu da satır sayısına
# eşittir çünkü ilk boyut dizi içindeki dizilerin pointerlarını tutar bu da satır sayıma eşit
m = len(numpy_array1)
n = len(numpy_array2)
k = len(numpy_array3)
print(m)
print(n)
print(k)

5
1
2


In [17]:
a = np.arange(10)
print(f"a = {a}")
c = a[2:7:1] # 2. indisden başlayıp 1 indis geçerek 7. indise kadar diziye kesik atıyoruz  yeni dizi oluşturyoruz
print(f"c = {c}")
d = a[2:8:2] #2. indisden başlayıp 2 indis geçerek 8. indise kadar diziye kesik atıyoruz bununla yeni dizi oluşturyoruz
print(f"d= {d}")
w  = np.arange(18)
print(f"w = {w}")
q = w[0:17:3]
print(f"q = {q}")


a = [0 1 2 3 4 5 6 7 8 9]
c = [2 3 4 5 6]
d= [2 4 6]
w = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
q = [ 0  3  6  9 12 15]


In [25]:
w  = np.arange(18)
print(f"w = {w}")
z = -w
print(f"z = {z}")
x = np.sum(w)
print(f"sum of w = {x}")
x = np.sum(z)
print(f"sum of z = {x}")
x = np.mean(w)
print(f"mean of w = {x}")
x = w**2
print(f"w^2 = {x}")


w = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
z = [  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17]
sum of w = 153
sum of z = -153
mean of w = 8.5
w^2 = [  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289]


In [37]:
k =np.arange(20)
print(f"k = {k}")
l = k[0:20:6]
print(f"l = {l}")
m = k[0:10:3]
print(f"m = {m}")
n = k[0:7:2]
print(f"n = {n}")
print(f"m+n = {m+n}")
print(f"m*n = {m*n}")
print(f"l/n = {l/n}")
print(f"l/m = {l/m}")


k = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
l = [ 0  6 12 18]
m = [0 3 6 9]
n = [0 2 4 6]
m+n = [ 0  5 10 15]
m*n = [ 0  6 24 54]
l/n = [nan  3.  3.  3.]
l/m = [nan  2.  2.  2.]


C:\Users\erkme\AppData\Local\Temp\ipykernel_16948\2694456872.py:11: RuntimeWarning: invalid value encountered in divide
  print(f"l/n = {l/n}")
C:\Users\erkme\AppData\Local\Temp\ipykernel_16948\2694456872.py:12: RuntimeWarning: invalid value encountered in divide
  print(f"l/m = {l/m}")


Multiple Variable Linear Regression

In [1]:
import numpy as np

In [2]:
x_train = np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35],[957,3,1,28],[1758,4,1,38]])
y_train = np.array([460,232,178,198,442])

In [3]:
#parametrelerimiz için W ,b için başlangıç değerleri
b_init = 678.345
W_init = np.array([0.425457,20.346126,7.253751,-10.98248])

In [4]:
# tahmin yapmam lazım sonra yaptığım tahminle hatayı hesaplayıp costu bulmam  gradiyan hesaplamam lazım sonra bu gradiyan ile
#cost üzerinde gradient ile inerek costun min değerini bulup bu W ve b yi bulmam lazım  
def predict(x_train,W_init,b_init):
    p =np.dot(x_train,W_init)+b_init
    return p   

In [5]:
def compute_cost(x_train,y_train,W_init,b_init):
    cost = 0 
    m = x_train.shape[0]
    for i in range(m):
        predict1 = predict(x_train[i],W_init,b_init)#yukarıda yazdığımız tahmin fonksiyonunu çağırarak başlangıç parametreleriyle tahmin üretiyoruz
        cost = cost +(predict1 - y_train[i])**2 
    cost = cost /2*m
    return cost  

In [6]:
def gradient(x_train, y_train, W_init, b_init):
    m = x_train.shape[0]
    d_W = np.zeros((4,))
    d_b = 0

    for i in range(m):
        error = predict(x_train[i], W_init, b_init) - y_train[i]
        for j in range(4):
            d_W += error * x_train[i, j]
        d_b += error

    d_W /= m
    d_b /= m

    return d_W, d_b

In [7]:
def gradient_descent(x_train,y_train,W_init,b_init):
    iterations =10
    alfa =5.0e-9 
    
    for i in range(iterations):
        d_W,d_b = gradient(x_train,y_train,W_init,b_init)
        W_init = W_init-alfa*d_W
        b_init = b_init-alfa*d_b
        #print(f" W  = {W_init}")
        #print(f" b = {b_init}")
        print(f"cost = {compute_cost(x_train,y_train,W_init,b_init)}")

    return W_init,b_init
    
    

In [8]:
w,b= gradient_descent(x_train,y_train,W_init,b_init)

cost = 5199699.758410335
cost = 5085018.858593855
cost = 4973026.7310209945
cost = 4863660.3355847495
cost = 4756858.11019661
cost = 4652559.936133389
cost = 4550707.10419656
cost = 4451242.281664956
cost = 4354109.480022342
cost = 4259254.023441588


Sigmoid Function

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
input_array = np.array([7,8,9])
exp_array = np.exp(input_array)
#exp() fonksiyonu bir numpy arrayinin içindeki elemanların exponansiyellerini hesaplayan bir fonksiyon 

In [4]:
print("inputs :",input_array)
print("outputs :",exp_array)

inputs : [7 8 9]
outputs : [1096.63315843 2980.95798704 8103.08392758]


In [72]:
def sigmoid(z):
    g = 1 /( 1 + np.exp(-z))
    return g

In [73]:
z = np.arange(-5,5)
y = sigmoid(z)
print("inputs",z)
print("outputs",y)

inputs [-5 -4 -3 -2 -1  0  1  2  3  4]
outputs [0.00669285 0.01798621 0.04742587 0.11920292 0.26894142 0.5
 0.73105858 0.88079708 0.95257413 0.98201379]


In [74]:
np.set_printoptions(precision=3) 
print("Input (z), Output (sigmoid(z))")
print(np.c_[z, y])

Input (z), Output (sigmoid(z))
[[-5.     0.007]
 [-4.     0.018]
 [-3.     0.047]
 [-2.     0.119]
 [-1.     0.269]
 [ 0.     0.5  ]
 [ 1.     0.731]
 [ 2.     0.881]
 [ 3.     0.953]
 [ 4.     0.982]]


Logistic Regression

In [75]:
import numpy as np


In [76]:
X_train = np.array([[0.5, 1.5], [1,1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y_train = np.array([0, 0, 0, 1, 1, 1])

In [77]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [78]:
def gradient(x,y,w,b):
    m = X_train.shape[0]
    n = X_train.shape[1]
    dj_W = np.zeros((n,))
    dj_b=0
    for i in range(m):
        predict = sigmoid(np.dot(x[i],w) + b) # w ile x değerlerini vektörel olarak çarptım daha sonra b değerini ekledim w'nin başlangıç değeri için tahminimi bulmuş oldum 
        error = predict - y[i]
        for j in range(n):
            dj_W[j] += error*x[i][j]
        dj_b +=error

    dj_W =dj_W /m
    dj_b =dj_b /m
    return  dj_W,dj_b

In [69]:
X_tmp = np.array([[0.5, 1.5], [1,1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y_tmp = np.array([0, 0, 0, 1, 1, 1])
w_tmp = np.array([2.,3.])
b_tmp = 1.
dj_dw_tmp,dj_db_tmp = gradient(X_tmp, y_tmp, w_tmp, b_tmp)
print(f"dj_db: {dj_db_tmp}" )
print(f"dj_dw: {dj_dw_tmp.tolist()}" )

dj_db: 0.49861806546328574
dj_dw: [0.498333393278696, 0.49883942983996693]


In [79]:
def gradient_descent(x,y,W,b):
    alpha = 0.1
    for i in range (10000):
          dj_W ,dj_b=gradient(x,y,W,b)

          W = W - alpha * dj_W
          b = b - alpha* dj_b
    return W,b

In [80]:
w_tmp  = np.zeros_like(X_train[0])
b_tmp  = 0.
w_out, b_out = gradient_descent(X_train, y_train, w_tmp, b_tmp) 
print(f"\nupdated parameters: w:{w_out}, b:{b_out}")


updated parameters: w:[5.281 5.078], b:-14.222409982019837
